name: docs

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Tag
      id: get_tag
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
    - name: Run Jazzy
      uses: swiftpackages/publish-jazzy-docs@v2.0.0
      with:
        args: --module_version ${{ steps.get_tag.outputs.tag }} --github_file_prefix https://github.com/swiftpackages/DotEnv/tree/${{ steps.get_tag.outputs.tag }} --output docs/${{ steps.get_tag.outputs.tag }}
        personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
