name: docs

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Jazzy
      uses: swiftpackages/publish-jazzy-docs@v2.0.0
      with:
        args: --module_version main --github_file_prefix https://github.com/swiftpackages/DotEnv/tree/main --output docs/main
        personal_access_token: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
