name: registry

on:
  release:
    types: [published]
  workflow_run:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Swift Package Registry
        uses: twodayslate/swift-package-registry@v0.0.2
