name: ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: swift-actions/setup-swift@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
